### ISSUE TITLE
Use of API

### ISSUE THREAD

**Issue by RickCogley** [neatnik/salty#3]
Hi, I'd like to pass the api a  payload and key, via say URL params, and get back the compressed version of the encrypted string. Is this possible?

**Comment by newbold** [comment]
Absolutely, yes! Here is an extremely lightweight implementation of just such an API:

```
<?php

include('salty.php');

header("Content-type: text/plain");

if(!isset($_REQUEST['payload'])) die('Missing payload parameter.');
if(!isset($_REQUEST['key'])) die('Missing key parameter.');

die(salty_encrypt($_REQUEST['payload'], salty_key($_REQUEST['key'])));

?>
```

If this were saved as `script.php` and you made a request to `/script.php?payload=this+is+a+secret&key=secret_key`, you’ll receive the compressed encrypted string as the output.

Your question made me realize that the core `salty.php` script is just a small collection of functions, and not an API — which it probably should be. So I can work on making that enhancement, but in the interim the script above should meet your short-term need. Let me know if you run into any issues with it or have any other questions.

**Comment by RickCogley** [comment]
thanks so much for the quick response!

> So I can work on making that enhancement
sounds great!

> the script above should meet your short-term need
it does work exactly as expected, thanks!

**Comment by RickCogley** [comment]
I noticed that when I send URL encoded payload strings via this method, what gets shown on decryption is the URL encoded string. Does it need a decode somewhere I guess?

**Comment by newbold** [comment]
Ah, good catch — the GET method is going to introduce complexities with urlencoding. If you’re switching over to the [POST implementation](https://github.com/neatnik/salty/issues/5#issuecomment-908909858) then it should no longer be an issue, since you can pass raw strings (including unencoded punctuation and such), and the `http_build_query` function being used in conjunction with curl will handle the encoding for you. If this isn't working for you, though, just let me know and we can dig further into other adjustments.

**Comment by RickCogley** [comment]
I was able to just use POST from our database against the `script.php`, putting the params in the body set as "form" type.

**Comment by newbold** [comment]
The API code now now bundled into the main Salty script and I've added a note about how to use it in README.md. Let me know if you have any questions or issues with it!
